/** @type {import('tailwindcss').Config} */
export default {
  content: [
    './index.html',
    './src/**/*.{ts,tsx}',
    './**/*.{ts,tsx}',
    '!./node_modules/**',
    '!./dist/**',
  ],
  theme: {
    extend: {
      fontFamily: {
        sans: ['DM Sans', 'sans-serif'],
        display: ['Space Grotesk', 'sans-serif'],
        headline: ['Manrope', 'sans-serif'],
        body: ['Inter', 'sans-serif'],
        label: ['Inter', 'sans-serif'],
      },
      colors: {
        'primary': '#4e45e4',
        'primary-dim': '#4135d8',
        'primary-fixed': '#bdbaff',
        'primary-fixed-dim': '#adabff',
        'primary-container': '#bdbaff',
        'on-primary': '#fbf7ff',
        'on-primary-fixed': '#17008c',
        'on-primary-fixed-variant': '#3220cb',
        'on-primary-container': '#270ac3',
        'secondary': '#742fe5',
        'secondary-dim': '#681ad9',
        'secondary-fixed': '#eaddff',
        'secondary-fixed-dim': '#deccff',
        'secondary-container': '#eaddff',
        'on-secondary': '#fdf7ff',
        'on-secondary-fixed': '#5100b3',
        'on-secondary-fixed-variant': '#702ae1',
        'on-secondary-container': '#6617d7',
        'tertiary': '#005bc4',
        'tertiary-dim': '#004fad',
        'tertiary-fixed': '#98b8ff',
        'tertiary-fixed-dim': '#81aaff',
        'tertiary-container': '#98b8ff',
        'on-tertiary': '#f9f8ff',
        'on-tertiary-fixed': '#001f4b',
        'on-tertiary-fixed-variant': '#003c87',
        'on-tertiary-container': '#003476',
        'surface': '#faf8ff',
        'surface-dim': '#cdd9ff',
        'surface-bright': '#faf8ff',
        'surface-tint': '#4e45e4',
        'surface-variant': '#d9e2ff',
        'surface-container': '#eaedff',
        'surface-container-low': '#f2f3ff',
        'surface-container-lowest': '#ffffff',
        'surface-container-high': '#e2e7ff',
        'surface-container-highest': '#d9e2ff',
        'on-surface': '#213156',
        'on-surface-variant': '#4f5e86',
        'on-background': '#213156',
        'background': '#faf8ff',
        'outline': '#6a7aa3',
        'outline-variant': '#a2b1dd',
        'error': '#ac3149',
        'error-dim': '#770326',
        'error-container': '#f76a80',
        'on-error': '#fff7f7',
        'on-error-container': '#68001f',
        'inverse-surface': '#060e20',
        'inverse-on-surface': '#959cb5',
        'inverse-primary': '#8582ff',
      },
    },
  },
  plugins: [],
};
